# Today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [8]:
import numpy as np
numpy_version = np.__version__
print(f'NumPy version is: {numpy_version}')

NumPy version is: 1.26.4


#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [12]:
A = np.arange(1,17)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

[ 1  3  5  7  9 11 13 15]


In [29]:
arr = np.array(A)
condition = (arr%2) != 0
odd_values = arr[condition]
print(odd_values)

[ 1  3  5  7  9 11 13 15]


#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


In [49]:
arr = np.array(odd_values)
result = np.zeros(arr.size * 2, dtype=arr.dtype)
result[::2] = arr 
print("Modified array:", result)

Modified array: [ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [50]:
B = result.reshape(4,4)
B

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]
 [ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [53]:
stacked_array = np.vstack((B,B))
stacked_array

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

In [57]:
transposed_arr = stacked_array.T
transposed_arr[:, 1::2] = transposed_arr[::-1, 1::2]
modified_arr = transposed_arr.T
print("Modified vertically stacked array with alternating column order:") 
print(modified_arr)

Modified vertically stacked array with alternating column order:
[[ 1  0  3  0]
 [ 0  7  0  5]
 [ 9  0 11  0]
 [ 0 15  0 13]
 [ 1  0  3  0]
 [ 0  7  0  5]
 [ 9  0 11  0]
 [ 0 15  0 13]]


#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

In [65]:
Mean = np.mean(modified_arr)
print(f'Mean: {Mean}')
Median = np.median(modified_arr)
print(f'Mean: {Median}')
Mode = np.mode(modified_arr)
print(f'Mode: {Mode}')


Mean: 4.0
Mean: 0.5


AttributeError: module 'numpy' has no attribute 'mode'

#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

Random Element Array : [15  0  5  3  0]


In [ ]:
## write code here


#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [94]:
def BCE(y, y_hat):
    ## write code here
    

In [95]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.011179895048277702
