In [27]:
# importing numpy as np
# numpy performs fast operations because of vectorization
# can be treated as vectors and matrices from linear algebra

import numpy as np

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [4]:
# square of each element

%timeit [i**2 for i in lst]

570 ns ± 11.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
arr = np.array(lst)

In [12]:
%timeit arr**2

552 ns ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
lst +[1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [15]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
# numpy arrray can be n dimensional >> is homogenous array

In [19]:
# different ways to create np array
# 1. np.array()
# 2. np.arange()

In [20]:
l = [1,5,8,9]
np_arr = np.array(l)

In [21]:
np_arr

array([1, 5, 8, 9])

In [22]:
type(np_arr)

numpy.ndarray

In [23]:
np_arr.ndim

1

In [24]:
np_arr.shape

(4,)

In [25]:
# another way of creating np array

new_arr = np.arange(3,11,2)

In [26]:
new_arr

array([3, 5, 7, 9])

In [27]:
lst_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [28]:
arr_2d = np.array(lst_2d)

In [29]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr_2d.ndim

2

In [31]:
arr_2d.shape

(3, 3)

In [33]:
# special arrays in Numpy
# zeros()
# ones()
# diag()
# identity()

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.ones((5,5))
# you can also use fill value

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
np.identity(4)
# note: identity matrix is always a square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
#Indexing in Array

In [48]:
#generate a random number between 10 to 100
np.random.randint(10,100)

42

In [50]:
new_arr = np.random.randint(1,10, (5,4))

In [51]:
new_arr.shape

(5, 4)

In [53]:
# first row
new_arr[0]

array([5, 4, 2, 5])

In [55]:
new_arr

array([[5, 4, 2, 5],
       [3, 7, 8, 4],
       [8, 6, 3, 5],
       [4, 9, 9, 9],
       [9, 8, 1, 2]])

In [57]:
# second last row
new_arr[-2]

array([4, 9, 9, 9])

In [59]:
# array slicing
# arr[start_row_index:end_row_index + 1, start_column_index:end_column_index + 1]

In [62]:
new_arr[2:5, 1:4]

array([[6, 3, 5],
       [9, 9, 9],
       [8, 1, 2]])

In [63]:
# 3rd column only
new_arr[:,2]

array([2, 8, 3, 9, 1])

In [64]:
new_arr[0,0] = 0

In [65]:
new_arr

array([[0, 4, 2, 5],
       [3, 7, 8, 4],
       [8, 6, 3, 5],
       [4, 9, 9, 9],
       [9, 8, 1, 2]])

In [70]:
# masking
mask = new_arr > 5
print(mask)

[[False False False False]
 [False  True  True False]
 [ True  True False False]
 [False  True  True  True]
 [ True  True False False]]


In [73]:
# true = 1; false = 0
# get all the values greater than 5
np.sum(mask)

9

In [74]:
# get all the values greater than 5
new_arr[mask]

array([7, 8, 8, 6, 9, 9, 9, 9, 8])

In [75]:
# to make a particular section zero
new_arr[2: , 2:] = 0

In [76]:
new_arr

array([[0, 4, 2, 5],
       [3, 7, 8, 4],
       [8, 6, 0, 0],
       [4, 9, 0, 0],
       [9, 8, 0, 0]])

In [77]:
# basic operations in Array

In [12]:
a = np.array([10,20,30,40])
b = np.arange(1, 5)

In [6]:
a

array([10, 20, 30, 40])

In [13]:
b

array([1, 2, 3, 4])

In [18]:
a+b # note that both the arrays will have to be of same shape

array([11, 22, 33, 44])

In [15]:
a-b

array([ 9, 18, 27, 36])

In [16]:
a*b

array([ 10,  40,  90, 160])

In [17]:
b**2

array([ 1,  4,  9, 16])

In [19]:
# masking
a> 15

array([False,  True,  True,  True])

In [20]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [22]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [29]:
A = np.random.randint(0,5, (3,4))
B = np.random.randint(0,5, (4,2))

In [30]:
A

array([[1, 0, 2, 4],
       [0, 4, 1, 0],
       [3, 3, 2, 1]])

In [31]:
B

array([[1, 1],
       [2, 1],
       [2, 2],
       [0, 0]])

In [32]:
# dot product
# here the first element of the result is obtained by multiplying each elements in 1st row of first array with 
# each element in 1st column of second array and then adding it.
np.dot(A,B)

array([[ 5,  5],
       [10,  6],
       [13, 10]])

In [33]:
A = np.arange(0,24)

In [34]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
A = A.reshape(6,4)

In [36]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [38]:
np.sum(A)

276

In [39]:
np.max(A)

23

In [40]:
np.mean(A)

11.5

In [41]:
np.std(A)

6.922186552431729

In [42]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
# sum column wise
np.sum(A, axis=0)

array([60, 66, 72, 78])

In [45]:
# sum row wise
np.sum(A, axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [46]:
np.mean(A, axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [47]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
A.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [54]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
# transpose
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [55]:
A.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [62]:
# stacking of arrays - vstack, hstack

In [63]:
a = np.random.randint(0,10,(2,2))
b = np.random.randint(0,10,(2,2))

In [64]:
a

array([[5, 2],
       [9, 4]])

In [65]:
b

array([[3, 9],
       [2, 9]])

In [66]:
np.hstack((a,b))

array([[5, 2, 3, 9],
       [9, 4, 2, 9]])

In [67]:
np.vstack((a,b))

array([[5, 2],
       [9, 4],
       [3, 9],
       [2, 9]])

In [71]:
# Broadcasting - different shaped arrays can perform operations. 
# A small array can repeat itself and convert to the same shape as of another array.

In [72]:
A = np.random.randint(0,10, size=(3,3))
a = np.array([[1,2,3]])

In [73]:
A

array([[6, 6, 6],
       [3, 4, 3],
       [3, 1, 6]])

In [74]:
a

array([[1, 2, 3]])

In [75]:
print(A.shape, a.shape)

(3, 3) (1, 3)


In [77]:
A+a
# here even though there is just one row in a, 
# it will replicate itself into 3 rows with same content as the first row and make itself a 3*3 array and then add.

array([[7, 8, 9],
       [4, 6, 6],
       [4, 3, 9]])

In [78]:
a.T

array([[1],
       [2],
       [3]])

In [79]:
A+a.T # here its first transposed, broadcasted and then added.

array([[7, 7, 7],
       [5, 6, 5],
       [6, 4, 9]])

In [80]:
A+4

array([[10, 10, 10],
       [ 7,  8,  7],
       [ 7,  5, 10]])

In [84]:
# Vectorization - performing operations directly on arrays

In [83]:
p1 = np.array([1,2])
p2 = np.array([5,5])

In [86]:
s = 0
for i in range(2):
    s += (p2[i] - p1[i])**2
print(s**0.5)

5.0


In [89]:
# loop is not efficient
# here is the effiicent code using vectorization

In [93]:
np.sqrt(np.sum(p2-p1)**2)

7.0